### ISSUE TITLE
楼主版本一直要更新啊

### ISSUE THREAD

**Issue by zzq121410457** [KINGGUOKUN/Account#4]
最近一直打算用个适合自己的框架，看到你的框架很好~但是好像很久没更新了~希望群主建个群或者留个联系方式。

**Comment by KINGGUOKUN** [comment]
您想看到哪方面的更新？单体转微服务？升级到core3？没有建群，是因为感觉这个完全是不上台面的东西，就是一些个人的架构实践心得，里边东西少的可怜。外加自己比较佛性，忙的时候就少玩儿，闲下来，就折腾一下。当然，空闲之余，还是会不停更新的。
--我的联系方式：184494760（QQ）；KINGGUOKUN（WeChat）
